version: "3.8"

services:
  dokoga:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dokoga_app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    volumes:
      - dokoga_data:/app/data

volumes:
  dokoga_data:
    driver: local
