"""Integrity layer — read-only API over data/app/integrity.sqlite (procurement red flags +
ownership network + leak-free ML blend) and the LLM-judge (retrieve→narrate, reuses agent.generate).

Aggregations mirror the offline pipeline (scripts/integrity/*). Everything here is read-only;
data is regenerated by the scripts. Risk = signal, not accusation; the judge computes no numbers.
"""
import os, json, sqlite3, functools

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.abspath(os.path.join(HERE, "..", "data", "app"))
DB_PATH = os.path.join(DATA, "integrity.sqlite")
GEO = os.path.join(DATA, "bg_oblasti.geojson")


def _con():
    c = sqlite3.connect(DB_PATH)
    c.row_factory = sqlite3.Row
    return c


@functools.lru_cache(maxsize=1)
def _region_names():
    g = json.load(open(GEO, encoding="utf-8"))
    return sorted([f["properties"]["region_name"] for f in g["features"]], key=lambda s: -len(s))


def _region_of(buyer_name):
    if not buyer_name:
        return None
    u = buyer_name.upper()
    for r in _region_names():
        if r.upper() in u:
            return r
    return None


@functools.lru_cache(maxsize=1)
def _blend():
    con = _con()
    out = {}
    for r in con.execute("SELECT i.target_id id, i.score det, COALESCE(m.p_adverse,0) ml "
                         "FROM integrity_scores i LEFT JOIN ml_scores m ON i.target_id=m.contract_id "
                         "WHERE i.target_type='contract'"):
        out[r["id"]] = 0.7 * r["det"] + 0.3 * r["ml"]
    con.close()
    return out


def _ml_metrics():
    p = os.path.join(DATA, "ml_metrics.json")
    return json.load(open(p, encoding="utf-8")) if os.path.exists(p) else None


def summary():
    con = _con()
    tot = con.execute("SELECT COUNT(*) n, COALESCE(SUM(amount_eur),0) v FROM contracts").fetchone()
    k = {
        "contracts": tot["n"], "value_eur": round(tot["v"]),
        "organizations": con.execute("SELECT COUNT(*) FROM organizations").fetchone()[0],
        "buyers": con.execute("SELECT COUNT(DISTINCT buyer_eik) FROM contracts WHERE buyer_eik IS NOT NULL").fetchone()[0],
        "suppliers": con.execute("SELECT COUNT(DISTINCT supplier_eik) FROM contracts WHERE supplier_eik IS NOT NULL").fetchone()[0],
        "flags": con.execute("SELECT COUNT(*) FROM flags").fetchone()[0],
        "high": con.execute("SELECT COUNT(*) FROM integrity_scores WHERE level='high'").fetchone()[0],
        "single_bid_pct": round(100 * con.execute("SELECT COUNT(*) FROM contracts WHERE offers_count<=1").fetchone()[0] / max(1, tot["n"])),
    }
    fs = {r["code"]: r["n"] for r in con.execute("SELECT code,COUNT(*) n FROM flags GROUP BY code ORDER BY n DESC")}
    con.close()
    return {"kpis": k, "flags_summary": fs, "ml": _ml_metrics()}


def regions():
    con = _con(); B = _blend()
    names = list(_region_names())
    reg = {n: {"region_name": n, "contracts": 0, "value_eur": 0.0, "high": 0, "single": 0, "risk_sum": 0.0} for n in names}
    matched = total = 0
    for r in con.execute("SELECT id, buyer_name, amount_eur, offers_count FROM contracts"):
        total += 1
        rn = _region_of(r["buyer_name"])
        if not rn:
            continue
        matched += 1
        d = reg[rn]; d["contracts"] += 1; d["value_eur"] += r["amount_eur"] or 0
        b = B.get(r["id"], 0); d["risk_sum"] += b
        if (r["offers_count"] or 9) <= 1:
            d["single"] += 1
        if b >= 0.66:
            d["high"] += 1
    con.close()
    out = []
    for n, d in reg.items():
        c = d["contracts"]
        out.append({"region_name": n, "contracts": c, "value_eur": round(d["value_eur"]), "high": d["high"],
                    "single_bid_pct": round(100 * d["single"] / c) if c else 0,
                    "avg_risk": round(d["risk_sum"] / c, 3) if c else 0})
    return {"regions": out, "coverage_pct": round(100 * matched / max(1, total))}


def companies(limit=200):
    con = _con(); out = []
    q = ("SELECT c.supplier_eik eik, COALESCE(o.name,c.supplier_name) name, COUNT(*) n, "
         "COALESCE(SUM(c.amount_eur),0) won, COUNT(DISTINCT c.buyer_eik) buyers, "
         "SUM(CASE WHEN c.offers_count<=1 THEN 1 ELSE 0 END) single "
         "FROM contracts c LEFT JOIN organizations o ON c.supplier_eik=o.eik "
         "WHERE c.supplier_eik IS NOT NULL AND c.supplier_eik<>'0000000000' "
         "GROUP BY c.supplier_eik ORDER BY won DESC LIMIT ?")
    for r in con.execute(q, (limit,)):
        nf = con.execute("SELECT COUNT(*) n FROM flags WHERE target_type='contract' AND target_id IN "
                         "(SELECT id FROM contracts WHERE supplier_eik=?)", (r["eik"],)).fetchone()["n"]
        out.append({"eik": r["eik"], "name": r["name"], "contracts": r["n"], "won_eur": round(r["won"]),
                    "buyers": r["buyers"], "single_bid_pct": round(100 * r["single"] / max(1, r["n"])), "flags": nf})
    con.close()
    return out


def buyers(limit=200):
    con = _con(); out = []
    q = ("SELECT buyer_eik eik, MAX(buyer_name) name, COUNT(*) n, COALESCE(SUM(amount_eur),0) spend, "
         "COUNT(DISTINCT supplier_eik) sup, SUM(CASE WHEN offers_count<=1 THEN 1 ELSE 0 END) single "
         "FROM contracts WHERE buyer_eik IS NOT NULL GROUP BY buyer_eik ORDER BY spend DESC LIMIT ?")
    for r in con.execute(q, (limit,)):
        top = con.execute("SELECT COALESCE(SUM(amount_eur),0) s FROM contracts WHERE buyer_eik=? "
                          "GROUP BY supplier_eik ORDER BY s DESC LIMIT 1", (r["eik"],)).fetchone()
        share = round(100 * (top["s"] / r["spend"])) if r["spend"] else 0
        out.append({"eik": r["eik"], "name": r["name"], "contracts": r["n"], "spend_eur": round(r["spend"]),
                    "suppliers": r["sup"], "single_bid_pct": round(100 * r["single"] / max(1, r["n"])),
                    "top_supplier_share": share, "region": _region_of(r["name"])})
    con.close()
    return out


def sectors():
    con = _con(); out = []
    for r in con.execute("SELECT substr(cpv,1,2) div, COUNT(*) n, COALESCE(SUM(amount_eur),0) v, "
                         "SUM(CASE WHEN offers_count<=1 THEN 1 ELSE 0 END) single FROM contracts "
                         "WHERE cpv IS NOT NULL GROUP BY div ORDER BY v DESC LIMIT 30"):
        out.append({"cpv_division": r["div"], "contracts": r["n"], "value_eur": round(r["v"]),
                    "single_bid_pct": round(100 * r["single"] / max(1, r["n"]))})
    con.close()
    return out


def top_risk(limit=60):
    con = _con(); B = _blend(); out = []
    for cid, b in sorted(B.items(), key=lambda kv: -kv[1])[:limit]:
        c = con.execute("SELECT supplier_name,buyer_name,amount_eur,cpv FROM contracts WHERE id=?", (cid,)).fetchone()
        codes = [x["code"] for x in con.execute("SELECT DISTINCT code FROM flags WHERE target_type='contract' AND target_id=?", (cid,))]
        out.append({"id": cid, "supplier": c["supplier_name"], "buyer": c["buyer_name"],
                    "amount_eur": round(c["amount_eur"]) if c["amount_eur"] else None, "cpv": c["cpv"],
                    "blended": round(b, 3), "codes": codes})
    con.close()
    return out


def network(limit=50):
    con = _con(); out = []
    for r in con.execute("SELECT evidence FROM flags WHERE code='shared_owner_cross_tenders' ORDER BY severity DESC LIMIT ?", (limit,)):
        e = json.loads(r["evidence"])
        out.append({"person": e["person_name"], "id_type": e["id_type"], "count": e["company_count"],
                    "companies": [{"eik": c["eik"], "name": c["name"]} for c in e["winning_companies"]]})
    con.close()
    return out


def _contract_bundle(con, cid):
    c = con.execute("SELECT * FROM contracts WHERE id=?", (cid,)).fetchone()
    if not c:
        return None
    flags = [{"code": r["code"], "evidence": json.loads(r["evidence"])}
             for r in con.execute("SELECT code,evidence FROM flags WHERE target_type='contract' AND target_id=?", (cid,))]
    sc = con.execute("SELECT score,level FROM integrity_scores WHERE target_type='contract' AND target_id=?", (cid,)).fetchone()
    ml = con.execute("SELECT p_adverse FROM ml_scores WHERE contract_id=?", (cid,)).fetchone()
    det = sc["score"] if sc else 0.0
    p = ml["p_adverse"] if ml else 0.0
    return {"type": "contract", "supplier": c["supplier_name"], "buyer": c["buyer_name"],
            "amount_eur": round(c["amount_eur"]) if c["amount_eur"] else None, "cpv": c["cpv"],
            "offers_count": c["offers_count"], "integrity_level": sc["level"] if sc else None,
            "integrity_score": det, "ml_p_adverse": p, "blended_risk": round(0.7 * det + 0.3 * p, 3), "flags": flags}


def _shared_owner_bundle(con):
    r = con.execute("SELECT evidence FROM flags WHERE code='shared_owner_cross_tenders' ORDER BY severity DESC LIMIT 1").fetchone()
    if not r:
        return None
    e = json.loads(r["evidence"])
    return {"type": "shared_owner_across_winning_firms", "person_name": e["person_name"],
            "id_type": e["id_type"], "winning_companies": e["winning_companies"], "company_count": e["company_count"]}


_NARRATE = """Ти си обясняващ асистент за прозрачност на обществените поръчки. Обясни на прост български
защо посоченото е маркирано като СИГНАЛ ЗА РИСК, използвайки САМО фактите и числата по-долу.
Правила: НЕ изчислявай и НЕ измисляй нови числа — ползвай само дадените. Това е обективен сигнал по
индикатори, НЕ е обвинение и НЕ е присъда. Пиши 3–5 изречения. Завърши с дисклеймър, че това е
автоматичен сигнал за проверка, а не доказателство за нарушение.

ДАННИ (JSON):
{data}

Обяснение:"""


def explain(target):
    """retrieve (deterministic) → narrate (LLM, computes nothing). Returns {bundle, narrative}."""
    import agent
    con = _con()
    bundle = _shared_owner_bundle(con) if target == "shared-owner" else _contract_bundle(con, target)
    con.close()
    if not bundle:
        return {"error": "no evidence", "bundle": None, "narrative": None}
    narrative = agent.generate(_NARRATE.format(data=json.dumps(bundle, ensure_ascii=False)))
    return {"bundle": bundle, "narrative": narrative}
