"""Integrity layer — read-only API over data/app/integrity.sqlite (procurement red flags +
ownership network + leak-free ML blend) and the LLM-judge (retrieve→narrate, reuses agent.generate).

Aggregations mirror the offline pipeline (scripts/integrity/*). Everything here is read-only;
data is regenerated by the scripts. Risk = signal, not accusation; the judge computes no numbers.
"""
import os, re, json, math, sqlite3, functools

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.abspath(os.path.join(HERE, "..", "data", "app"))
DB_PATH = os.path.join(DATA, "integrity.sqlite")
GEO = os.path.join(DATA, "bg_oblasti.geojson")

# The raw .sqlite is gitignored (large); the repo ships a gzipped copy. On a fresh checkout/deploy
# inflate it so the analytics endpoints have data without any manual step. Also re-inflate if the
# file exists but is tiny - sqlite auto-creates an empty 0-byte db on first connect, which would
# otherwise leave analytics empty forever.
if os.path.exists(DB_PATH + ".gz") and (not os.path.exists(DB_PATH) or os.path.getsize(DB_PATH) < 1_000_000):
    import gzip
    import shutil
    with gzip.open(DB_PATH + ".gz", "rb") as _fin, open(DB_PATH, "wb") as _fout:
        shutil.copyfileobj(_fin, _fout)


def _con():
    c = sqlite3.connect(DB_PATH)
    c.row_factory = sqlite3.Row
    return c


@functools.lru_cache(maxsize=1)
def _region_names():
    g = json.load(open(GEO, encoding="utf-8"))
    return sorted([f["properties"]["region_name"] for f in g["features"]], key=lambda s: -len(s))


# buyer-name aliases the plain substring match misses (Sofia city bodies, common variants)
_ALIASES = {
    "СТОЛИЧНА": "София (столица)", "СОФИЯ-ГРАД": "София (столица)", "ГР. СОФИЯ": "София (столица)",
    "ГРАД СОФИЯ": "София (столица)", "СО РАЙОН": "София (столица)", "РАЙОН ": "София (столица)",
    "ВЕЛИКОТЪРНОВ": "Велико Търново", "СТАРОЗАГОР": "Стара Загора",
}


def _region_of(buyer_name):
    if not buyer_name:
        return None
    u = buyer_name.upper()
    for kw, rn in _ALIASES.items():
        if kw in u:
            return rn
    for r in _region_names():
        if r.upper() in u:
            return r
    return None


@functools.lru_cache(maxsize=1)
def _blend():
    con = _con()
    out = {}
    for r in con.execute("SELECT i.target_id id, i.score det, COALESCE(m.p_adverse,0) ml "
                         "FROM integrity_scores i LEFT JOIN ml_scores m ON i.target_id=m.contract_id "
                         "WHERE i.target_type='contract'"):
        out[r["id"]] = 0.7 * r["det"] + 0.3 * r["ml"]
    con.close()
    return out


def _obshtina(buyer_name):
    """Extract the municipality from the buyer name (accurate; only for municipal buyers)."""
    if not buyer_name:
        return None
    if "СТОЛИЧНА ОБЩИНА" in buyer_name.upper():
        return "Столична община (София)"
    m = re.search(r"(?i)ОБЩИНА\s+([\w\.\- ]+)", buyer_name)
    if m:
        name = re.split(r"[,\"„(]", m.group(1))[0].strip()
        words = name.split()[:3]
        return "Община " + " ".join(w.capitalize() for w in words)
    return None


def _ml_metrics():
    p = os.path.join(DATA, "ml_metrics.json")
    return json.load(open(p, encoding="utf-8")) if os.path.exists(p) else None


def summary():
    con = _con()
    tot = con.execute("SELECT COUNT(*) n, COALESCE(SUM(amount_eur),0) v FROM contracts").fetchone()
    k = {
        "contracts": tot["n"], "value_eur": round(tot["v"]),
        "organizations": con.execute("SELECT COUNT(*) FROM organizations").fetchone()[0],
        "buyers": con.execute("SELECT COUNT(DISTINCT buyer_eik) FROM contracts WHERE buyer_eik IS NOT NULL").fetchone()[0],
        "suppliers": con.execute("SELECT COUNT(DISTINCT supplier_eik) FROM contracts WHERE supplier_eik IS NOT NULL").fetchone()[0],
        "flags": con.execute("SELECT COUNT(*) FROM flags").fetchone()[0],
        "high": con.execute("SELECT COUNT(*) FROM integrity_scores WHERE level='high'").fetchone()[0],
        "single_bid_pct": round(100 * con.execute("SELECT COUNT(*) FROM contracts WHERE offers_count<=1").fetchone()[0] / max(1, tot["n"])),
    }
    fs = {r["code"]: r["n"] for r in con.execute("SELECT code,COUNT(*) n FROM flags GROUP BY code ORDER BY n DESC")}
    con.close()
    return {"kpis": k, "flags_summary": fs, "ml": _ml_metrics()}


def regions():
    con = _con(); B = _blend()
    names = list(_region_names())
    reg = {n: {"region_name": n, "contracts": 0, "value_eur": 0.0, "high": 0, "single": 0,
               "single_value": 0.0, "risk_sum": 0.0} for n in names}
    matched = total = 0
    for r in con.execute("SELECT id, buyer_name, amount_eur, offers_count FROM contracts"):
        total += 1
        rn = _region_of(r["buyer_name"])
        if not rn:
            continue
        matched += 1
        amt = r["amount_eur"] or 0
        d = reg[rn]; d["contracts"] += 1; d["value_eur"] += amt
        b = B.get(r["id"], 0); d["risk_sum"] += b
        if (r["offers_count"] or 9) <= 1:
            d["single"] += 1; d["single_value"] += amt
        if b >= 0.66:
            d["high"] += 1
    con.close()
    out = []
    for n, d in reg.items():
        c = d["contracts"]; v = d["value_eur"]
        out.append({"region_name": n, "contracts": c, "value_eur": round(v), "high": d["high"],
                    "single_bid_pct": round(100 * d["single"] / c) if c else 0,
                    # money-weighted, differentiating: share of contract VALUE awarded with a single bidder
                    "risk_index": round(100 * d["single_value"] / v) if v else 0,
                    "high_pct": round(100 * d["high"] / c, 1) if c else 0,
                    "avg_risk": round(d["risk_sum"] / c, 3) if c else 0})
    return {"regions": out, "coverage_pct": round(100 * matched / max(1, total))}


def companies(limit=200):
    con = _con(); out = []
    q = ("SELECT c.supplier_eik eik, COALESCE(o.name,c.supplier_name) name, COUNT(*) n, "
         "COALESCE(SUM(c.amount_eur),0) won, COUNT(DISTINCT c.buyer_eik) buyers, "
         "SUM(CASE WHEN c.offers_count<=1 THEN 1 ELSE 0 END) single "
         "FROM contracts c LEFT JOIN organizations o ON c.supplier_eik=o.eik "
         "WHERE c.supplier_eik IS NOT NULL AND c.supplier_eik<>'0000000000' "
         "GROUP BY c.supplier_eik ORDER BY won DESC LIMIT ?")
    for r in con.execute(q, (limit,)):
        nf = con.execute("SELECT COUNT(*) n FROM flags WHERE target_type='contract' AND target_id IN "
                         "(SELECT id FROM contracts WHERE supplier_eik=?)", (r["eik"],)).fetchone()["n"]
        out.append({"eik": r["eik"], "name": r["name"], "contracts": r["n"], "won_eur": round(r["won"]),
                    "buyers": r["buyers"], "single_bid_pct": round(100 * r["single"] / max(1, r["n"])), "flags": nf})
    con.close()
    return out


def buyers(limit=200):
    con = _con(); out = []
    q = ("SELECT buyer_eik eik, MAX(buyer_name) name, COUNT(*) n, COALESCE(SUM(amount_eur),0) spend, "
         "COUNT(DISTINCT supplier_eik) sup, SUM(CASE WHEN offers_count<=1 THEN 1 ELSE 0 END) single "
         "FROM contracts WHERE buyer_eik IS NOT NULL GROUP BY buyer_eik ORDER BY spend DESC LIMIT ?")
    for r in con.execute(q, (limit,)):
        top = con.execute("SELECT COALESCE(SUM(amount_eur),0) s FROM contracts WHERE buyer_eik=? "
                          "GROUP BY supplier_eik ORDER BY s DESC LIMIT 1", (r["eik"],)).fetchone()
        share = round(100 * (top["s"] / r["spend"])) if r["spend"] else 0
        out.append({"eik": r["eik"], "name": r["name"], "contracts": r["n"], "spend_eur": round(r["spend"]),
                    "suppliers": r["sup"], "single_bid_pct": round(100 * r["single"] / max(1, r["n"])),
                    "top_supplier_share": share, "region": _region_of(r["name"])})
    con.close()
    return out


def sectors():
    con = _con(); out = []
    for r in con.execute("SELECT substr(cpv,1,2) div, COUNT(*) n, COALESCE(SUM(amount_eur),0) v, "
                         "SUM(CASE WHEN offers_count<=1 THEN 1 ELSE 0 END) single FROM contracts "
                         "WHERE cpv IS NOT NULL GROUP BY div ORDER BY v DESC LIMIT 30"):
        out.append({"cpv_division": r["div"], "contracts": r["n"], "value_eur": round(r["v"]),
                    "single_bid_pct": round(100 * r["single"] / max(1, r["n"]))})
    con.close()
    return out


def top_risk(limit=60):
    con = _con(); B = _blend(); out = []
    for cid, b in sorted(B.items(), key=lambda kv: -kv[1])[:limit]:
        c = con.execute("SELECT supplier_name,buyer_name,amount_eur,cpv FROM contracts WHERE id=?", (cid,)).fetchone()
        codes = [x["code"] for x in con.execute("SELECT DISTINCT code FROM flags WHERE target_type='contract' AND target_id=?", (cid,))]
        out.append({"id": cid, "supplier": c["supplier_name"], "buyer": c["buyer_name"],
                    "amount_eur": round(c["amount_eur"]) if c["amount_eur"] else None, "cpv": c["cpv"],
                    "blended": round(b, 3), "codes": codes})
    con.close()
    return out


def _reasons(flags):
    """Human Bulgarian evidence lines from a contract's flag evidence (no invented numbers)."""
    out = []
    for f in flags:
        c, e = f["code"], f["evidence"]
        if c == "single_bidding":
            out.append("единствена подадена оферта")
        elif c == "low_competition":
            out.append(f"само {e.get('offers_count')} оферти")
        elif c == "short_tender_window":
            out.append(f"{e.get('gap_days')} дни за подаване (под {e.get('min_days')})")
        elif c == "price_anomaly_cpv":
            out.append(f"{e.get('ratio_to_median')}× над медианата за CPV {e.get('cpv')}")
        elif c == "annex_value_inflation":
            out.append(f"+{round(e.get('max_annex_inflation', 0) * 100)}% увеличение чрез анекс")
    return out


def cases(limit=40, min_value=50000):
    """Investigations feed: material (big-money) suspicious contracts. Ranked by risk WEIGHTED BY MONEY
    (corruption = lots of money + red flags), value-floored to drop noise, deduped per supplier."""
    con = _con(); B = _blend()
    amts = {r["id"]: (r["amount_eur"] or 0) for r in con.execute("SELECT id, amount_eur FROM contracts")}

    def mscore(cid, b):
        a = amts.get(cid, 0)
        vf = max(0.0, min(1.0, (math.log10(a) / 7) if a > 0 else 0))  # €10M -> ~1.0, €100k -> ~0.71
        return b * (0.4 + 0.6 * vf)

    ranked = sorted((kv for kv in B.items() if amts.get(kv[0], 0) >= min_value), key=lambda kv: -mscore(*kv))
    out = []; seen = set()
    for cid, b in ranked:
        if len(out) >= limit:
            break
        c = con.execute("SELECT supplier_name,buyer_name,amount_eur,cpv FROM contracts WHERE id=?", (cid,)).fetchone()
        key = (c["supplier_name"] or "").strip().upper()
        if key and key in seen:
            continue
        seen.add(key)
        flags = [{"code": r["code"], "evidence": json.loads(r["evidence"])}
                 for r in con.execute("SELECT code,evidence FROM flags WHERE target_type='contract' AND target_id=?", (cid,))]
        out.append({"id": cid, "supplier": c["supplier_name"], "buyer": c["buyer_name"],
                    "obshtina": _obshtina(c["buyer_name"]),
                    "amount_eur": round(c["amount_eur"]) if c["amount_eur"] else None, "cpv": c["cpv"],
                    "blended": round(b, 3), "level": "high" if b >= 0.66 else "med" if b >= 0.33 else "low",
                    "codes": [f["code"] for f in flags], "reasons": _reasons(flags)})
    con.close()
    return out


def network(limit=50):
    """Shared-owner links that matter: keep only links whose co-owned firms are themselves flagged,
    ranked by total money won. A benign shared owner (no red flags, ordinary contracts) is not corruption."""
    con = _con(); raw = []
    for r in con.execute("SELECT evidence FROM flags WHERE code='shared_owner_cross_tenders'"):
        e = json.loads(r["evidence"])
        won = flags = 0
        for comp in e["winning_companies"]:
            won += con.execute("SELECT COALESCE(SUM(amount_eur),0) s FROM contracts WHERE supplier_eik=?", (comp["eik"],)).fetchone()["s"]
            flags += con.execute("SELECT COUNT(*) n FROM flags WHERE target_type='contract' AND target_id IN "
                                 "(SELECT id FROM contracts WHERE supplier_eik=?)", (comp["eik"],)).fetchone()["n"]
        if flags == 0 or won < 1_000_000:
            continue  # benign or small-money co-ownership is not a meaningful corruption signal
        raw.append({"person": e["person_name"], "id_type": e["id_type"], "count": e["company_count"],
                    "won_eur": round(won), "flags": flags,
                    "companies": [{"eik": c["eik"], "name": c["name"]} for c in e["winning_companies"]]})
    con.close()
    raw.sort(key=lambda x: -x["won_eur"])
    return raw[:limit]


def companies_ranked():
    """EVERY winning company with a 0-100 risk (max blended risk across its contracts). Full list,
    sorted high->low so you can find any company - most are clean (low/0)."""
    con = _con(); B = _blend()
    fl = {}
    for r in con.execute("SELECT c.supplier_eik eik, COUNT(*) n FROM flags f JOIN contracts c ON f.target_id=c.id "
                         "WHERE f.target_type='contract' GROUP BY c.supplier_eik"):
        fl[r["eik"]] = r["n"]
    agg = {}
    for r in con.execute("SELECT id, supplier_eik eik, supplier_name nm, amount_eur, offers_count FROM contracts "
                         "WHERE supplier_eik IS NOT NULL AND supplier_eik<>'0000000000'"):
        d = agg.setdefault(r["eik"], {"name": None, "n": 0, "won": 0.0, "single": 0, "risk": 0.0})
        d["n"] += 1; d["won"] += r["amount_eur"] or 0
        if (r["offers_count"] or 9) <= 1:
            d["single"] += 1
        b = B.get(r["id"], 0)
        if b > d["risk"]:
            d["risk"] = b
        if r["nm"] and not d["name"]:
            d["name"] = r["nm"]
    con.close()
    out = [{"eik": e, "name": d["name"], "contracts": d["n"], "won_eur": round(d["won"]),
            "single_bid_pct": round(100 * d["single"] / max(1, d["n"])), "flags": fl.get(e, 0),
            "risk_pct": round(100 * d["risk"])} for e, d in agg.items()]
    out.sort(key=lambda x: (-x["risk_pct"], -x["won_eur"]))
    return out


# ML model is a SUPPORTING signal; this documents WHY it contributes (honest, no fake "corruption %").
ML_WHY = ("ML добавката (LightGBM, leak-free ROC-AUC 0.86) предсказва дали договорът ще бъде съществено "
          "изменян (анекси) - сигнал за лошо управление. Тежи 30%, не определя флаг. Водещите признаци са: "
          "историческа честота на изменения на изпълнителя и възложителя, стойност, брой оференти, "
          "отстранени оферти, CPV сектор. 'Защо' за всеки случай идва от обективните флагове по-долу.")


def company_detail(eik):
    con = _con(); B = _blend()
    base = con.execute("SELECT MAX(supplier_name) nm, COUNT(*) n, COALESCE(SUM(amount_eur),0) won, "
                       "COUNT(DISTINCT buyer_eik) buyers, SUM(CASE WHEN offers_count<=1 THEN 1 ELSE 0 END) single "
                       "FROM contracts WHERE supplier_eik=?", (eik,)).fetchone()
    if not base or not base["n"]:
        con.close(); return None
    org = con.execute("SELECT name,legal_form FROM organizations WHERE eik=?", (eik,)).fetchone()
    flb = {r["code"]: r["n"] for r in con.execute(
        "SELECT code,COUNT(*) n FROM flags WHERE target_type='contract' AND target_id IN "
        "(SELECT id FROM contracts WHERE supplier_eik=?) GROUP BY code", (eik,))}
    susp = []; maxrisk = 0.0
    for r in con.execute("SELECT id,buyer_name,amount_eur,cpv FROM contracts WHERE supplier_eik=?", (eik,)):
        b = B.get(r["id"], 0); maxrisk = max(maxrisk, b)
        fr = [{"code": x["code"], "evidence": json.loads(x["evidence"])}
              for x in con.execute("SELECT code,evidence FROM flags WHERE target_type='contract' AND target_id=?", (r["id"],))]
        if fr:
            susp.append({"id": r["id"], "buyer": r["buyer_name"],
                         "amount_eur": round(r["amount_eur"]) if r["amount_eur"] else None,
                         "obshtina": _obshtina(r["buyer_name"]), "reasons": _reasons(fr), "risk": round(b, 3)})
    susp.sort(key=lambda x: -x["risk"]); susp = susp[:20]
    owners = [{"person_key": r["person_key"], "name": r["name"], "role": r["role"], "id_type": r["indent_type"]}
              for r in con.execute("SELECT r.person_key,r.role,p.name,p.indent_type FROM roles r "
                                   "JOIN persons p ON r.person_key=p.person_key WHERE r.eik=?", (eik,))]
    by_year = []
    for r in con.execute("SELECT substr(contract_date,1,4) y, COALESCE(SUM(amount_eur),0) s, COUNT(*) n "
                         "FROM contracts WHERE supplier_eik=? AND contract_date IS NOT NULL GROUP BY y ORDER BY y", (eik,)):
        if r["y"]:
            by_year.append({"year": r["y"], "value_eur": round(r["s"]), "contracts": r["n"]})
    con.close()
    return {"eik": eik, "name": (org["name"] if org else None) or base["nm"], "legal_form": org["legal_form"] if org else None,
            "contracts": base["n"], "won_eur": round(base["won"]), "buyers": base["buyers"],
            "single_bid_pct": round(100 * base["single"] / max(1, base["n"])), "risk_pct": round(100 * maxrisk),
            "flags": flb, "owners": owners, "suspicious": susp, "by_year": by_year,
            "income": None, "ml_why": ML_WHY}


def person_detail(key):
    con = _con()
    p = con.execute("SELECT name,indent_type FROM persons WHERE person_key=?", (key,)).fetchone()
    comps = []
    for r in con.execute("SELECT r.eik, r.role FROM roles r WHERE r.person_key=?", (key,)):
        w = con.execute("SELECT MAX(supplier_name) nm, COALESCE(SUM(amount_eur),0) s, COUNT(*) n "
                        "FROM contracts WHERE supplier_eik=?", (r["eik"],)).fetchone()
        org = con.execute("SELECT name FROM organizations WHERE eik=?", (r["eik"],)).fetchone()
        comps.append({"eik": r["eik"], "name": (org["name"] if org else None) or w["nm"] or r["eik"],
                      "role": r["role"], "won_eur": round(w["s"]), "contracts": w["n"]})
    con.close()
    comps.sort(key=lambda x: -x["won_eur"])
    return {"person_key": key, "name": p["name"] if p else None, "id_type": p["indent_type"] if p else None,
            "companies": comps, "total_won_eur": sum(c["won_eur"] for c in comps), "income": None}


def _contract_bundle(con, cid):
    c = con.execute("SELECT * FROM contracts WHERE id=?", (cid,)).fetchone()
    if not c:
        return None
    flags = [{"code": r["code"], "evidence": json.loads(r["evidence"])}
             for r in con.execute("SELECT code,evidence FROM flags WHERE target_type='contract' AND target_id=?", (cid,))]
    sc = con.execute("SELECT score,level FROM integrity_scores WHERE target_type='contract' AND target_id=?", (cid,)).fetchone()
    ml = con.execute("SELECT p_adverse FROM ml_scores WHERE contract_id=?", (cid,)).fetchone()
    det = sc["score"] if sc else 0.0
    p = ml["p_adverse"] if ml else 0.0
    return {"type": "contract", "supplier": c["supplier_name"], "buyer": c["buyer_name"],
            "amount_eur": round(c["amount_eur"]) if c["amount_eur"] else None, "cpv": c["cpv"],
            "offers_count": c["offers_count"], "integrity_level": sc["level"] if sc else None,
            "integrity_score": det, "ml_p_adverse": p, "blended_risk": round(0.7 * det + 0.3 * p, 3), "flags": flags}


def _company_bundle(con, eik):
    a = con.execute("SELECT COUNT(*) n, COALESCE(SUM(amount_eur),0) won, COUNT(DISTINCT buyer_eik) buyers, "
                    "SUM(CASE WHEN offers_count<=1 THEN 1 ELSE 0 END) single, MAX(supplier_name) nm "
                    "FROM contracts WHERE supplier_eik=?", (eik,)).fetchone()
    org = con.execute("SELECT name FROM organizations WHERE eik=?", (eik,)).fetchone()
    fl = {r["code"]: r["n"] for r in con.execute(
        "SELECT code,COUNT(*) n FROM flags WHERE target_type='contract' AND target_id IN "
        "(SELECT id FROM contracts WHERE supplier_eik=?) GROUP BY code", (eik,))}
    return {"type": "company", "eik": eik, "name": (org["name"] if org else None) or a["nm"],
            "contracts_won": a["n"], "won_eur": round(a["won"]), "distinct_buyers": a["buyers"],
            "single_bid_pct": round(100 * a["single"] / max(1, a["n"])), "flags": fl}


def _shared_owner_bundle(con):
    r = con.execute("SELECT evidence FROM flags WHERE code='shared_owner_cross_tenders' ORDER BY severity DESC LIMIT 1").fetchone()
    if not r:
        return None
    e = json.loads(r["evidence"])
    return {"type": "shared_owner_across_winning_firms", "person_name": e["person_name"],
            "id_type": e["id_type"], "winning_companies": e["winning_companies"], "company_count": e["company_count"]}


_NARRATE = """Ти си обясняващ асистент за прозрачност на обществените поръчки. Обясни на прост български
защо посоченото е маркирано като СИГНАЛ ЗА РИСК, използвайки САМО фактите и числата по-долу.
Правила: НЕ изчислявай и НЕ измисляй нови числа — ползвай само дадените. Това е обективен сигнал по
индикатори, НЕ е обвинение и НЕ е присъда. Пиши 3–5 изречения. Завърши с дисклеймър, че това е
автоматичен сигнал за проверка, а не доказателство за нарушение.

ДАННИ (JSON):
{data}

Обяснение:"""


def explain(target):
    """retrieve (deterministic) → narrate (LLM, computes nothing). Returns {bundle, narrative}."""
    import agent
    con = _con()
    if target.startswith("company:"):
        bundle = _company_bundle(con, target.split(":", 1)[1])
    elif target == "shared-owner":
        bundle = _shared_owner_bundle(con)
    else:
        bundle = _contract_bundle(con, target)
    con.close()
    if not bundle:
        return {"error": "no evidence", "bundle": None, "narrative": None}
    narrative = agent.generate(_NARRATE.format(data=json.dumps(bundle, ensure_ascii=False)))
    return {"bundle": bundle, "narrative": narrative}
